apiVersion: v1 
kind: Service
metadata:
 name: noderedrepo-2
spec:
 type: LoadBalancer
 selector:
  app: noderedrepo-2
 ports:
 - protocol: TCP
   port: 80
   targetPort: 1880
---
kind: Deployment
apiVersion: apps/v1
metadata:
 name: noderedrepo-2
spec:
 replicas: 1
 selector:
  matchLabels:
   app: noderedrepo-2
 template:
  metadata:
   labels:
    app: noderedrepo-2
  spec:
   containers:
   - name: nodered-cluster
     image: gcr.io/synapses-323217/github.com/misbahhassan08/noderedrepo-2:latest
     ports:
     - containerPort: 1880